s = str("Hello World")
i = int(20)
f = float(20.7)
c = complex(20)
l = list(("apple", "banna", "cherry"))
t = tuple(("apple", "banna", "cherry"))
se = set(("apple", "banna", "cherry"))
d = dict(name="john", age=36)
r = range(6)
f = frozenset(("apple", "banana", "cherry"))
b = bool(5)
by = bytes(6)
bya = bytearray(5)
memo = memoryview(bytes(5))
print(s)
print(i)
print(f)
print(c)
print(l)
print(t)
print(se)
print(d)
print(r)
print(f)
print(b)
print(by)
print(bya)
print(memo )