a = int(input("Type a number:"))
b = int(input("Type another number:"))
print("Addition of two number:", a+b)
print("Subtraction of two number:", a-b)
print("Division of two number:", a/b)
print("Multiplication of two number:", a*b)
print("Remainder of two numbet:", a%b)
print("Muodule division of two number:", a//b)